### ISSUE TITLE
subsume: Investigate TF timeout and deletion of primary DB 

### ISSUE THREAD

**Issue by FelisiaM** [cloudfoundry/csb-brokerpak-azure#86] opened 2021-08-27 10:48 UTC
**Describe the bug**
There have been cases when the subsume operations have failed with the following errors and the primary DB has been deleted as a result:

```
Future#WaitForCompletion: context has been cancelled
```

or

```
Status=504 Code="GatewayTimeout" Message="The gateway did not receive a response from 'Microsoft.Sql'"
```

### Steps to reproduce
There is no scenario that can consistently reproduce it

### Expected
Error during subsume operation and all related resources should be still available.

### Actual
The primary DB was deleted 

**Notes**
- As part of #53 we confirmed that there is no relationship between the DB size/DTU and this failure.

**Comment by pivotal-marcela-campo** [comment] 2021-09-15 10:38
We’ve investigated this issue but could not reproduce it. If it does happen again, we would need more information to troubleshoot

* Logs with the terraform plan printed during subsume (with GSB_DEBUG=true)
* FOG settings - we are currently using all the defaults from the MASB broker, is there anything you are setting up differently? Anything that could have been configured via MASB broker or directly from the Azure portal/api?.
* Subscription settings - is there anything that is applied to  your across all your database servers as a subscription default? for example, threat detection policies and alike

**Comment by pivotal-marcela-campo** [comment] 2022-03-24 11:26
Closing this. Please re raise if needed.

**Closed by pivotal-marcela-campo** 2022-03-24 11:26 UTC
Labels: unscheduled
